# Generated by Django 5.0.7 on 2024-07-26 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
