# Generated by Django 5.0.7 on 2024-07-26 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_candidate_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='email',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='phone',
        ),
    ]
