# Generated by Django 5.0.7 on 2024-07-27 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_remove_candidate_email_remove_candidate_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='email',
            field=models.EmailField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
