# Generated by Django 5.0.7 on 2024-07-27 23:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0008_note_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
