# Generated by Django 5.0.7 on 2024-07-29 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0010_alter_candidate_uploaded_at_alter_note_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('UI/UX', 'UI/UX Designer'), ('Frontend', 'Frontend Developer'), ('Backend', 'Backend Developer'), ('Fullstack', 'Fullstack Developer'), ('DataScience', 'Data Scientist'), ('ProductManager', 'Product Manager')], default='Frontend', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitation_date', models.DateField()),
                ('candidate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitation', to='cv.candidate')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitation', to='cv.position')),
            ],
        ),
    ]
