# Generated by Django 5.0.7 on 2024-07-29 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0011_position_invitation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitation',
            old_name='invitation_date',
            new_name='interview_date',
        ),
    ]
