# Generated by Django 5.0.7 on 2024-08-01 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0012_rename_invitation_date_invitation_interview_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='interview_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='position',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
